# Generated by Django 5.1.4 on 2024-12-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("posted_time", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("pay", models.CharField(max_length=255)),
                ("employment_details", models.JSONField()),
                ("skills", models.JSONField()),
                ("job_description", models.TextField()),
                ("required_skills", models.JSONField()),
                ("preferred_skills", models.JSONField()),
                ("job_link", models.URLField()),
            ],
        ),
    ]
