# Generated by Django 5.1.4 on 2024-12-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobHandle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employment_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job", name="pay", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="preferred_skills",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="required_skills",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
